title: Haochen Wang's Homepage
page-top-title: Haochen Wang
top-section-bg-text: Computer Science
home-subtitle: Haochen Wang&ensp;|&ensp;王浩晨
copyright-text: '&copy; Haochen Wang 2026-2026. All Rights Reserved.'